version: '3.8'

services:
  # PostgreSQL - Main database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: real_jobs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Redis - Caching, rate limiting, and Celery broker
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # OpenSearch - Full-text search
  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  # MinIO - Object storage for development
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9090"

  # Celery Worker
  celery_worker:
    build: .
    depends_on:
      - redis
      - postgres
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/real_jobs
    volumes:
      - ./scrapper:/app/scrapper
      - ./app:/app/app
    command: >
      sh -c "python -c 'from app.database import initialize_database; initialize_database()' &&
             celery -A scrapper.celery_app worker --loglevel=info"

  # Celery Beat (Scheduler)
  celery_beat:
    build: .
    depends_on:
      - redis
      - postgres
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/real_jobs
    volumes:
      - ./scrapper:/app/scrapper
      - ./app:/app/app
    command: celery -A scrapper.celery_app beat --loglevel=info

  # Flower - Celery monitoring
  flower:
    build: .
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
    command: celery -A scrapper.celery_app flower

volumes:
  postgres_data:
  redis_data:
  opensearch_data:
  minio_data: